import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav >
          <div className="navbar">
            <span>Foodzie</span>
            <span>Popular</span>
            <span>Link B</span>
            <span>Link C</span>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
